---
name: Publish a new release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
        description: the release tag
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, win]
        arch: [x64]
    env:
      RELEASE_NAME: "askfmArchiver-${{ matrix.os }}-${{ matrix.arch }}"
    steps:
      - uses: actions/checkout@v3

      - name: Set release version for manual triggers
        if: "! startsWith(github.ref, 'refs/tags/')"
        run: echo "askfmArchiver_version=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV

      - name: Set release version for tag events
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "askfmArchiver_version=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Publish ${{ matrix.os }}-${{ matrix.arch }}
        run: >
          dotnet publish
          --configuration Release
          --output="./${{ env.RELEASE_NAME }}"
          --os ${{ matrix.os }}
          --arch ${{ matrix.arch }}
          --self-contained "-p:DebugSymbols=false;DebugType=none"
          ./askfmArchiver/askfmArchiver.csproj

      - name: Add README and LICENSE to release
        run: cp README.md LICENSE ./${{ env.RELEASE_NAME }}

      - name: Compress artifacts
        run: zip -qr ${{ env.RELEASE_NAME }}.zip ./${{ env.RELEASE_NAME }}

      - name: Get release notes
        run: |
          CHANGELOG=$(cat Changelog.md | grep -oPz '(?s)(?<=### ${{ env.askfmArchiver_version }}\n{2}).+?(?=\n{2,3}###)')
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "askfmArchiver ${{ env.askfmArchiver_version }}"
          files: "${{ env.RELEASE_NAME }}.zip"
          body: |
            ### Changelog:
            ${{ env.CHANGELOG }}
          draft: true
